# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
#

font_family CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12

confirm_os_window_close 0
background_opacity 0.7
background_blur 32
linux_display_server wayland
hide_window_decorations yes
copy_on_select yes
