
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty --single-instance"
local fileManager = "nautilus"
local menu        = "pkill wofi || " .. os.getenv("HOME") .. "/.config/wofi/scripts/launcher.sh"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function ()
   hl.exec_cmd("waybar & dunst & swayosd-server & hypridle & /usr/local/bin/hyprpaper & " .. os.getenv("HOME") .. "/.config/hypr/scripts/battery-monitor.sh &")
   hl.exec_cmd("wl-paste --watch cliphist store")
   hl.exec_cmd("hyprctl setcursor catppuccin-mocha-dark-cursors 28")
   hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
   hl.exec_cmd("hyprctl dispatch exec '[workspace special:term silent] kitty --single-instance'")
   hl.exec_cmd("sh -c 'sleep 1 && notify-send -t 3000 -u low \"Hyprland\" \"Ready\"'")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(cba6f7ee)", "rgba(f2cdcdee)"}, angle = 90 },
            inactive_border = "rgba(a6adc8aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 5,
            passes    = 2,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = 0,
        background_color        = "rgb(1e1e2e)",
    },
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "se",
        kb_variant = "",
        kb_model   = "",
        kb_options = "caps:escape",
        kb_rules   = "",

        follow_mouse = 0,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("sh -c 'swayosd-client --output-volume raise && wpctl set-mute @DEFAULT_AUDIO_SINK@ 0'"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"),       { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"),  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("swayosd-client --brightness raise"),          { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("swayosd-client --brightness lower"),          { locked = true, repeating = true })
hl.bind(mainMod .. " + L",      hl.dsp.exec_cmd("hyprlock"))

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Lid / dock handling

local function is_lid_closed()
    local f = io.open("/proc/acpi/button/lid/LID0/state")
    if not f then return false end
    local s = f:read("*l"); f:close()
    return s ~= nil and s:match("closed") ~= nil
end

local function first_external()
    for _, m in ipairs(hl.get_monitors()) do
        if m.name ~= "eDP-1" then return m end
    end
end

-- Monitor references appear as HL.Monitor userdata, tables, or plain strings
-- depending on the API call; normalize to the name string
local function monitor_name(m)
    if m == nil then return nil end
    if type(m) == "string" then return m end
    local ok, name = pcall(function() return m.name end)
    if ok then return name end
    return nil
end

local function is_special(name)
    return type(name) == "string" and name:match("^special") ~= nil
end

local LID_PARK_WS    = "11"  -- workspace kept on eDP-1 while lid is closed so 1-10 stay on external
local edp_workspaces = {}    -- restore list; cleared only on restore/reclaim, never by sweeps
local edp_active_ws  = nil

-- Monitor:set_workspace() silently no-ops, so activate via the focus dispatchers:
-- focus eDP-1 → switch workspace (created on the focused monitor) → focus back.
-- All within one synchronous block, so the focus hop is invisible.
local function activate_ws_on_edp(ws_name)
    if not hl.get_monitor("eDP-1") then return end
    local prev = hl.get_active_monitor()
    hl.dispatch(hl.dsp.focus({ monitor = "eDP-1" }))
    hl.dispatch(hl.dsp.focus({ workspace = tonumber(ws_name) or ws_name }))
    if prev and prev.name ~= "eDP-1" then
        hl.dispatch(hl.dsp.focus({ monitor = prev.name }))
    end
end

local function park_edp()
    activate_ws_on_edp(LID_PARK_WS)
end

-- Always park BEFORE sweeping: an enabled monitor must have an active workspace,
-- so moving eDP-1's active workspace away makes Hyprland spawn a fresh one there
-- (reentrant workspace.created churn that also invalidates workspace objects
-- mid-iteration). Parked first, all swept workspaces are inactive and move cleanly;
-- names are still collected before dispatching as a second guard.
local function park_and_sweep_edp(target)
    if #edp_workspaces == 0 then
        local edp = hl.get_monitor("eDP-1")
        edp_active_ws = edp and edp.active_workspace and edp.active_workspace.name
        if edp_active_ws == LID_PARK_WS then edp_active_ws = nil end
    end
    park_edp()
    local recorded = {}
    for _, name in ipairs(edp_workspaces) do recorded[name] = true end
    local to_move = {}
    for _, ws in ipairs(hl.get_workspaces()) do
        if monitor_name(ws.monitor) == "eDP-1" and ws.name ~= LID_PARK_WS and not is_special(ws.name) then
            table.insert(to_move, ws.name)
        end
    end
    for _, name in ipairs(to_move) do
        if not recorded[name] then table.insert(edp_workspaces, name) end
        hl.dispatch(hl.dsp.workspace.move({ workspace = name, monitor = target.name }))
    end
end

local function enable_edp()
    hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1, disabled = false })
end

local function restore_edp_workspaces()
    if #edp_workspaces == 0 then return end
    local active_on_external = {}
    for _, m in ipairs(hl.get_monitors()) do
        if m.name ~= "eDP-1" and m.active_workspace then
            active_on_external[m.active_workspace.name] = true
        end
    end
    local first_restored
    for _, name in ipairs(edp_workspaces) do
        if not active_on_external[name] then
            hl.dispatch(hl.dsp.workspace.move({ workspace = name, monitor = "eDP-1" }))
            if not first_restored then first_restored = name end
        end
    end
    -- Activate the workspace that was active before lid close, falling back to the first restored one
    local target = (edp_active_ws and not active_on_external[edp_active_ws]) and edp_active_ws or first_restored
    if target then activate_ws_on_edp(target) end
    edp_workspaces = {}
    edp_active_ws  = nil
end

local WALLPAPER = os.getenv("HOME") .. "/.config/backgrounds/nice-blue-background.png"

local function ensure_wallpaper()
    -- os.execute returns a number on Lua 5.1/LuaJIT but a boolean on 5.2+
    local ok = os.execute("pgrep -x hyprpaper >/dev/null 2>&1")
    if ok == true or ok == 0 then
        hl.exec_cmd("hyprctl hyprpaper reload ," .. WALLPAPER)
    else
        hl.exec_cmd("/usr/local/bin/hyprpaper")
    end
end

-- Lid / dock scenario matrix:
--   open → close (no dock)     switch:on Lid      no external → skip; workspaces stay on eDP-1
--   open → dock → close        switch:on Lid      park eDP-1 @ ws 11 + sweep
--   open → close → dock        monitor.added      park + sweep (fires once per dock monitor)
--   closed, partial undock     monitor.removed    externals remain → re-sweep orphans off eDP-1
--   closed, full undock        monitor.removed    reclaim all workspaces to eDP-1
--   closed + dock → open       switch:off Lid     restore swept workspaces to eDP-1
--   closed → new workspace     workspace.created  redirect to external
--   closed → new window        window.open        redirect; on park ws, move window itself
--   startup/reload, closed     load timer         park + sweep (reload wipes Lua state)
--   lid flaps within timers    all timers         re-check lid state before acting
--   sleep / resume             hypridle           lock + dpms only; monitor events as above
--
-- eDP-1 is kept enabled (not disabled) while lid is closed: disabling it causes
-- enterUnsafeState() on dock removal → crash in getViewsForWorkspace (aquamarine bug).
hl.bind("switch:on:Lid Switch", function()
    local ext = first_external()
    if not ext then return end
    park_and_sweep_edp(ext)
    hl.timer(function()
        if not is_lid_closed() then return end
        local ext2 = first_external()
        if ext2 then park_and_sweep_edp(ext2) end -- second pass: catch late arrivals
        ensure_wallpaper()
    end, { timeout = 800, type = "oneshot" })
end, { locked = true })

hl.bind("switch:off:Lid Switch", function()
    enable_edp()
    hl.timer(function()
        if is_lid_closed() then return end
        restore_edp_workspaces()
        ensure_wallpaper()
    end, { timeout = 800, type = "oneshot" })
end, { locked = true })

hl.on("monitor.removed", function()
    if not is_lid_closed() then return end
    if first_external() then
        -- Partial undock: Hyprland rehomes the removed monitor's workspaces on its own,
        -- possibly onto eDP-1 — sweep after it has finished.
        hl.timer(function()
            if not is_lid_closed() then return end
            local ext = first_external()
            if not ext then return end
            park_and_sweep_edp(ext)
        end, { timeout = 300, type = "oneshot" })
        return
    end
    enable_edp()
    hl.timer(function()
        -- Bail if externals reappeared meanwhile (suspend/resume, dock link retrain)
        if first_external() or not is_lid_closed() then return end
        if not hl.get_monitor("eDP-1") then return end
        local to_reclaim = {}
        for _, ws in ipairs(hl.get_workspaces()) do
            if not is_special(ws.name) then table.insert(to_reclaim, ws.name) end
        end
        for _, name in ipairs(to_reclaim) do
            hl.dispatch(hl.dsp.workspace.move({ workspace = name, monitor = "eDP-1" }))
        end
        local target = edp_active_ws or edp_workspaces[1]
        if not target then
            for _, name in ipairs(to_reclaim) do
                if name ~= LID_PARK_WS then target = name; break end
            end
        end
        if target then activate_ws_on_edp(target) end
        edp_workspaces = {}
        edp_active_ws  = nil
        ensure_wallpaper()
    end, { timeout = 800, type = "oneshot" })
end)

hl.on("monitor.added", function()
    if not is_lid_closed() then return end
    if not hl.get_monitor("eDP-1") then return end
    local ext = first_external()
    if not ext then return end
    park_and_sweep_edp(ext)
    hl.timer(ensure_wallpaper, { timeout = 800, type = "oneshot" })
end)

hl.on("workspace.created", function(ws)
    if not is_lid_closed() then return end
    if monitor_name(ws.monitor) ~= "eDP-1" then return end
    if ws.name == LID_PARK_WS or is_special(ws.name) then return end
    local ext = first_external()
    if not ext then return end
    -- Park first: moving eDP-1's active workspace away would spawn yet another
    -- workspace here and re-trigger this handler (infinite churn)
    park_edp()
    hl.dispatch(hl.dsp.workspace.move({ workspace = ws.name, monitor = ext.name }))
end)

hl.on("window.open", function(window)
    if not is_lid_closed() then return end
    local ws = window.workspace
    if not ws or monitor_name(ws.monitor) ~= "eDP-1" then return end
    local ext = first_external()
    if not ext then return end
    if ws.name == LID_PARK_WS then
        -- Focus was on the invisible eDP-1 (follow_mouse): the park workspace must stay,
        -- so move just the window to the external's visible workspace
        if window.address and ext.active_workspace then
            hl.exec_cmd(string.format("hyprctl dispatch movetoworkspacesilent %s,address:%s",
                ext.active_workspace.name, window.address))
        end
        return
    end
    hl.dispatch(hl.dsp.workspace.move({ workspace = ws.name, monitor = ext.name }))
end)

-- Startup / config reload while lid closed: no event fires and a reload wipes the
-- restore state above, so sweep once after monitors have settled.
hl.timer(function()
    if not is_lid_closed() then return end
    local ext = first_external()
    if not ext then return end
    park_and_sweep_edp(ext)
    ensure_wallpaper()
end, { timeout = 1000, type = "oneshot" })

-- Screenshots (grim + slurp + swappy)
-- Print: select area → annotate (draw, save with S, copy with Ctrl+C)
-- Super+Print: full screen → annotate
hl.bind("Print",              hl.dsp.exec_cmd("sh -c 'grim -g \"$(slurp)\" - | swappy -f -'"))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("sh -c 'grim - | swappy -f -'"))

-- Clipboard history (cliphist)
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("sh -c 'cliphist list | wofi --dmenu | cliphist decode | wl-copy'"))

-- Power/logout menu (wlogout)
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("pkill wlogout || wlogout"), { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

hl.window_rule({
    name  = "teams-pwa-workspace",
    match = { class = "crx__ompifgpmddkgmclendfeacglnodjjndh" },
    workspace = "2 silent",
})

hl.window_rule({
    name  = "outlook-pwa-workspace",
    match = { class = "crx__faolnafnngnfdaknnbpnkhgohbobgegn" },
    workspace = "2 silent",
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
