source = $HOME/.config/hypr/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
    no_fade_in = true
}

# BACKGROUND
background {
    monitor =
    path = ~/.config/backgrounds/nice-blue-background.png
    blur_passes = 2
    color = $base
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
    color = $text
    font_size = 72
    font_family = $font
    position = 0, 100
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B %Y")"
    color = $text
    font_size = 22
    font_family = $font
    position = 0, 30
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = $surface0
    font_color = $text
    fade_on_empty = false
    placeholder_text = <i>Password…</i>
    rounding = 8
    hide_input = false
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, -40
    halign = center
    valign = center
}
